---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "need4speed73/centos8-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    'vault-id': '/tmp/vault.pw'
verifier:
  name: ansible
